### ISSUE TITLE
大佬你好，我想问一下你安装的是什么版本的macOS呀

### ISSUE THREAD

**Issue by c1139676919** [Remik1r3n/e3-1231-v3-asus-b85-plus-rx560-opencore-efi#1]
感谢开源的EFI文件，昨天我已经写好macOS Ventura 13.4.1 (22F82)这个版本的镜像，但是没有安装（因为我新买的硬盘今天才到），是能够正常引导进入到安装的界面，就是不知道这个CPU能否支持到这个版本，所以来询问一下大佬是使用的什么版本的macOS。
另外能否加个联系方式，感谢。

**Comment by Remik1r3n** [comment]
草，我就随手一传当备份，真有人用啊

我早就不用那台电脑了，但我后来又改这个efi 改过很多遍，然后最后我用的是 Ventura。

待会我会把我最后一次更新的 efi 传一下。我最后一次更新的 efi我自己觉得写的很完美（）


________________________________
From: c1139676919 ***@***.***>
Sent: Monday, July 24, 2023 9:19:27 AM
To: Remik1r3n/e3-1231-v3-asus-b85-plus-rx560-opencore-efi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Remik1r3n/e3-1231-v3-asus-b85-plus-rx560-opencore-efi] 大佬你好，我想问一下你安装的是什么版本的macOS呀 (Issue #1)


感谢开源的EFI文件，昨天我已经写好macOS Ventura 13.4.1 (22F82)这个版本的镜像，但是没有安装，是能够正常引导进入到安装的界面，就是不知道这个CPU能否支持到这个版本，所以来询问一下大佬是使用的什么版本的macOS

―

**Comment by c1139676919** [comment]
@Remik1r3n  我从你的github个人信息找到推特，然后从推特你的推文说会全部同步到b站，我又转到b站，然后私信你b站提示我得先转正😂，方便加个联系方式吗

**Comment by Remik1r3n** [comment]
我主要用 ***@***.***。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by c1139676919** [comment]
@Remik1r3n 主要是用邮箱吗   这个邮箱显示的是***

**Comment by Remik1r3n** [comment]
***@***.***

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by c1139676919** [comment]
![image](https://github.com/Remik1r3n/e3-1231-v3-asus-b85-plus-rx560-opencore-efi/assets/43144608/746b1ec0-168e-443c-a8d4-82be63c6c7c3)
很尴尬

**Comment by Remik1r3n** [comment]
草，GitHub 真安全啊（
remik1r3n @ outlook .com

**Comment by c1139676919** [comment]
不用微信和qq的吗😂  我就用上面那个邮箱联系你还是？

**Comment by Remik1r3n** [comment]
先和我发个邮件，我用邮件给你发我微信吧。这里是公开的，任何人都能看见，不适合公开微信。

**Comment by c1139676919** [comment]
给你发了邮件，查收一下哈
